name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: install numpy
        run : pip install numpy
      - name: python scripts
        run: |
          import numpy as np
          print(np.random.randn(10))
